package de.fhdortmund.mystudyapp.notification.model;

/**
 * All notification types that can be generated by the system.
 * Each maps to a specific user action or system event.
 */
public enum NotificationType {
    /** Event was approved by admin and is now PUBLISHED */
    EVENT_APPROVED,
    /** Event was rejected by admin */
    EVENT_REJECTED,
    /** User was promoted from WAITLISTED to GOING */
    WAITLIST_PROMOTED,
    /** Someone left a review on the user's event */
    NEW_REVIEW,
    /** User's trust level was promoted to TRUSTED_HOST */
    TRUST_PROMOTED,
    /** An event the user RSVP'd to was cancelled by the host */
    EVENT_CANCELLED,
    /** Another attendee cancelled their RSVP (host notification) */
    RSVP_CANCELLED,
    /** User received a new report resolution update */
    REPORT_RESOLVED
}


