CREATE TABLE students
(
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(100)NOT NULL,
    email        VARCHAR(150) UNIQUE NOT NULL,
    password     VARCHAR(255),
    profile_info CLOB,
    flame_score  NUMBER    DEFAULT 0,
    trust_score  NUMBER    DEFAULT 0,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE professors
(
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(100),
    email        VARCHAR(150) UNIQUE,
    password     VARCHAR(255),
    profile_info CLOB,
    verifide NUMBER(1) DEFAULT 1,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE events(
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(150),
    description CLOB,
    location VARCHAR2(150),
    date_time TIMESTAMP,
    max_participants Number,
    created_by NUMBER,
    CONSTRAINT fk_event_student FOREIGN KEY (created_by) REFERENCES students(id)
);

CREATE  TABLE  event_participants(
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id NUMBER,
    student_id NUMBER,
    joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    rating NUMBER(1),

    CONSTRAINT fk_ep_event FOREIGN KEY (event_id) REFERENCES events(id),
    CONSTRAINT fk_ep_student FOREIGN KEY (student_id) REFERENCES students(id),
    CONSTRAINT uq_ep UNIQUE (event_id, student_id)
);

CREATE TABLE posts(
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content CLOB,
    author_student_id NUMBER,
    author_professor_id NUMBER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE comments(
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id NUMBER,
    content CLOB,
    author_student_id NUMBER,
    author_professor_id NUMBER,
    CONSTRAINT fk_comment_post FOREIGN KEY (post_id) REFERENCES posts(id)

);

CREATE TABLE likes(
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id NUMBER,
    student_id NUMBER,

    CONSTRAINT fk_like_post FOREIGN KEY (post_id) REFERENCES posts(id),
    CONSTRAINT fk_like_student FOREIGN KEY (student_id) REFERENCES students(id),
    CONSTRAINT uq_like UNIQUE (post_id, student_id)

);
CREATE TABLE flames(
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_student_id NUMBER,
    to_student_id NUMBER,
    CONSTRAINT fk_flame_from FOREIGN KEY (from_student_id) REFERENCES students(id),
    CONSTRAINT fk_flame_to FOREIGN KEY (to_student_id) REFERENCES students(id)

);
CREATE TABLE trusts(
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    professor_id NUMBER,
    student_id NUMBER,

    CONSTRAINT fk_trust_prof FOREIGN KEY (professor_id) REFERENCES professors(id),
    CONSTRAINT fk_trust_student FOREIGN KEY (student_id) REFERENCES students(id),
    CONSTRAINT uq_trust UNIQUE (professor_id, student_id)
);

CREATE TABLE polls(
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question CLOB,
    created_by NUMBER,

    CONSTRAINT fk_poll_prof FOREIGN KEY (created_by) REFERENCES professors(id)
);
CREATE TABLE poll_options
(
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poll_id     NUMBER,
    option_text VARCHAR2(255),
    CONSTRAINT fk_option_poll FOREIGN KEY (poll_id) REFERENCES polls (id)
);
CREATE TABLE messages(
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id NUMBER,
    receiver_id NUMBER,
    content CLOB,
    sent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_msg_sender FOREIGN KEY (sender_id) REFERENCES students(id),
    CONSTRAINT fk_msg_receiver FOREIGN KEY (receiver_id) REFERENCES students(id)

);

