server:
  port: ${ASTA_SERVER_PORT:8082}

spring:
  application:
    name: backend-asta

# Custom MQTT properties
mqtt:
  broker-url: tcp://${MQTT_HOST:localhost}:1883
  client-id: backend-asta-publisher
  topic:
    events: mystudyapp/events